version: "3.7"
services:
  app:
    build:
      args:
        user: stas
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: appimage
    container_name: app-php
    restart: "on-failure"
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - appnet

  nginx:
    image: nginx:alpine
    container_name: app-nginx
    restart: unless-stopped
    restart: "on-failure"
    ports:
      - 80:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - appnet

networks:
  appnet:
    driver: bridge
